# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Saliha Irem BESIK
email: saliha.irem.besik@informatik.hu-berlin.de
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://irembesik.github.io/" # the base hostname & protocol for your site
twitter_username: ""
github_username: "irembesik"

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"



# Build settings
markdown: kramdown
